# Generated by Django 2.0.4 on 2018-05-17 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facebook', models.CharField(max_length=300)),
                ('twitter', models.CharField(max_length=300)),
                ('instagram', models.CharField(max_length=300)),
                ('img_url', models.CharField(default='None', max_length=1000)),
                ('about', models.TextField(default='Not given by the author but obviously he/she must be awesome!!s', max_length=2000)),
                ('user', models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=1000)),
                ('ip_address', models.CharField(max_length=20)),
                ('time', models.CharField(max_length=100)),
                ('city', models.CharField(default='None', max_length=100)),
                ('country', models.CharField(default='None', max_length=100)),
                ('isp', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt', models.TextField(max_length=300)),
                ('writer_name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=200)),
                ('abstract_img', models.CharField(default='None', max_length=200)),
                ('abstract', models.CharField(default='None', max_length=1000)),
                ('algorithm_type', models.CharField(default='None', max_length=50)),
                ('upload_date', models.CharField(default='Thu May 17 19:33:21 2018', max_length=50)),
                ('github', models.CharField(default='None', max_length=200)),
                ('content', models.TextField(default='None', max_length=10000)),
                ('author', models.ForeignKey(on_delete='models.CASCADE', to='blg.Author')),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(max_length=500)),
                ('twitter', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('contact', models.TextField(default='None', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blg.Topic'),
        ),
    ]
