# Generated by Django 2.0.4 on 2018-05-14 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='abstract',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
