# Generated by Django 2.0.4 on 2018-05-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0002_auto_20180517_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='footer',
            field=models.TextField(default='None'),
        ),
        migrations.AddField(
            model_name='websitedetail',
            name='header',
            field=models.TextField(default='None'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='upload_date',
            field=models.CharField(default='Thu May 17 20:17:56 2018', max_length=50),
        ),
    ]
