# Generated by Django 2.0.4 on 2018-05-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0002_topic_abstract'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='abstract_img',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
