# Generated by Django 2.0.4 on 2018-05-18 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0003_auto_20180517_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='img_url',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='topic',
            name='upload_date',
            field=models.CharField(default='Fri May 18 10:48:54 2018', max_length=50),
        ),
    ]
