# Generated by Django 2.0.4 on 2018-05-18 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0005_auto_20180518_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='topic',
            name='upload_date',
            field=models.CharField(default='Sat May 19 00:54:31 2018', max_length=50),
        ),
    ]
