# Generated by Django 2.0.4 on 2018-05-15 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0005_auto_20180515_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='img_url',
            field=models.CharField(default='None', max_length=1000),
        ),
    ]
