# Generated by Django 2.0.4 on 2018-05-15 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0006_author_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.CharField(default='Not given by the author but obviously he/she must be awesome!!s', max_length=2000),
        ),
    ]
