# Generated by Django 2.0.4 on 2018-05-15 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0008_remove_topic_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blg.Author'),
            preserve_default=False,
        ),
    ]
