# Generated by Django 2.0.4 on 2018-05-15 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0009_topic_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='author',
        ),
    ]
