# Generated by Django 2.0.4 on 2018-05-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0010_remove_topic_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='author',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
