# Generated by Django 2.0.4 on 2018-05-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0011_topic_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='data_upload',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
