# Generated by Django 2.0.4 on 2018-05-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0015_topic_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(default='None', max_length=3000),
        ),
    ]
