# Generated by Django 2.0.4 on 2018-05-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0016_auto_20180515_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmt', models.TextField(max_length=300)),
                ('writer_name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blg.Topic')),
            ],
        ),
    ]
