# Generated by Django 2.0.4 on 2018-05-16 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0018_auto_20180516_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='upload_date',
            field=models.CharField(default='Wed May 16 12:53:03 2018', max_length=50),
        ),
    ]
