# Generated by Django 2.0.4 on 2018-05-16 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0019_auto_20180516_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=models.TextField(default='None', max_length=10000),
        ),
        migrations.AlterField(
            model_name='topic',
            name='upload_date',
            field=models.CharField(default='Wed May 16 14:38:12 2018', max_length=50),
        ),
    ]
