# Generated by Django 2.0.4 on 2018-05-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0020_auto_20180516_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_agent', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='upload_date',
            field=models.CharField(default='Wed May 16 15:29:33 2018', max_length=50),
        ),
    ]
