# Generated by Django 2.0.4 on 2018-05-16 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0021_auto_20180516_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user_agent',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='topic',
            name='upload_date',
            field=models.CharField(default='Wed May 16 15:41:56 2018', max_length=50),
        ),
    ]
