# Generated by Django 2.0.4 on 2018-05-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0024_auto_20180516_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='upload_date',
            field=models.CharField(default='Wed May 16 18:51:44 2018', max_length=50),
        ),
    ]
