# Generated by Django 2.0.4 on 2018-05-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0025_auto_20180516_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='time',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='upload_date',
            field=models.CharField(default='Wed May 16 18:55:14 2018', max_length=50),
        ),
    ]
