# Generated by Django 2.0.4 on 2018-05-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0026_auto_20180516_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_website', models.TextField(max_length=500)),
                ('twitter', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='topic',
            name='upload_date',
            field=models.CharField(default='Wed May 16 19:46:52 2018', max_length=50),
        ),
    ]
