# Generated by Django 2.0.4 on 2018-05-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0028_auto_20180516_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='client',
            name='isp',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='topic',
            name='upload_date',
            field=models.CharField(default='Wed May 16 21:51:05 2018', max_length=50),
        ),
    ]
