# Generated by Django 2.0.4 on 2018-05-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0029_auto_20180516_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='upload_date',
            field=models.CharField(default='Wed May 16 21:51:16 2018', max_length=50),
        ),
    ]
