# Generated by Django 2.0.4 on 2018-05-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blg', '0030_auto_20180516_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitedetail',
            name='contact',
            field=models.TextField(default='None', max_length=500),
        ),
        migrations.AlterField(
            model_name='topic',
            name='upload_date',
            field=models.CharField(default='Thu May 17 00:22:43 2018', max_length=50),
        ),
    ]
